# Generated by Django 6.1 on 2026-08-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='priority',
        ),
    ]
